[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crapssim-api"
version = "0.2.0"
description = "CrapsSim HTTP API adapter"
readme = "../README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "crapssim>=0.4.0",
    "typing_extensions",
    "fastapi",
    "pydantic",
    "uvicorn",
]

[project.optional-dependencies]
api = [
    "fastapi",
    "pydantic",
    "uvicorn",
    "typing_extensions",
]
